services:
  # PostgreSQL Database
    postgres:
        image: postgres:16-alpine
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # No default database - databases are created by database_manager.py
        ports:
        -   5436:5432
        volumes:
        -   postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: [CMD-SHELL, 'pg_isready -U ${POSTGRES_USER}']
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    postgres_data:
