"""Pydantic models for the OmniPath parquet serving API.

These schemas are the source of the autogenerated OpenAPI document used by
Swagger UI at `/api/docs`.
"""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator


class APIModel(BaseModel):
    """Base model: keep unknown engine fields in responses and requests."""

    model_config = ConfigDict(extra="allow", populate_by_name=True)


class HealthResponse(APIModel):
    status: str
    engine: str = "duckdb-parquet"
    timestamp: float | None = None


class ErrorResponse(APIModel):
    error: str | None = None
    detail: str | None = None


# Entity collections a detail tab can page on its own.
DetailField = Literal["identifiers", "entityAttributes"]


class EntitySearchCursor(APIModel):
    """Where a search continues: its match phase and the entities already returned."""

    phase: Literal["all", "key", "prefix", "contains"]
    offset: int = Field(ge=0)
    queryKey: str


class SearchFilters(APIModel):
    """One internal filter contract, accepting historical wire aliases once."""

    reference_entity_keys: list[str] = Field(default_factory=list)
    protein_entity_keys: list[str] = Field(default_factory=list)
    transcript_entity_keys: list[str] = Field(default_factory=list)
    isoform_identifiers: list[str] = Field(
        default_factory=list, description="Exact namespace:id; unspecified forms do not match."
    )
    molecular_endpoint_mode: Literal["any", "both", "source", "target"] = "any"
    entity_ids: list[str] = Field(default_factory=list)
    entity_pks: list[str] = Field(default_factory=list)
    scope_entity_ids: list[str] = Field(default_factory=list)
    entity_types: list[str] = Field(default_factory=list)
    sources: list[str] = Field(default_factory=list)
    taxonomy_ids: list[str] = Field(default_factory=list)
    predicates: list[str] = Field(default_factory=list)
    relation_categories: list[str] = Field(default_factory=list)
    object_aspect_qualifier: list[str] = Field(default_factory=list)
    object_direction_qualifier: list[str] = Field(default_factory=list)
    causal_mechanism_qualifier: list[str] = Field(default_factory=list)
    interaction_types: list[str] = Field(default_factory=list)
    annotation_term_ids: list[str] = Field(default_factory=list)
    gene_mode: Literal["any", "both", "source", "source_only", "target", "target_only"] = "any"
    scope_endpoint_mode: Literal[
        "any", "both", "source", "source_only", "target", "target_only"
    ] = "any"
    is_directed: bool | None = None
    sign: int | None = None
    signs: list[int] = Field(default_factory=list)
    min_evidence_count: int | None = Field(default=None, ge=0)

    @model_validator(mode="before")
    @classmethod
    def normalize_aliases(cls, value: Any) -> Any:
        if not isinstance(value, dict):
            return value
        data = dict(value)
        aliases = {
            "entity_ids": ("entities", "genes", "entityIds"),
            "entity_pks": ("entityPks",),
            "entity_types": ("entityTypes",),
            "sources": ("resources",),
            "taxonomy_ids": ("taxonomyIds", "ncbi_tax_id"),
            "relation_categories": ("categories",),
            "interaction_types": ("interactionTypes",),
            "annotation_term_ids": ("annotationTermIds",),
        }
        for canonical, legacy in aliases.items():
            merged = []
            for key in (canonical, *legacy):
                values = data.pop(key, [])
                if values is None:
                    values = []
                if not isinstance(values, list):
                    raise ValueError(f"{key} must be a list")
                for item in values:
                    if not isinstance(item, (str, int)) or isinstance(item, bool):
                        raise ValueError(f"{key} must contain strings or integers")
                    text = str(item).strip()
                    if text and text not in merged:
                        merged.append(text)
            data[canonical] = merged
        if "endpointMode" in data:
            mode = data.pop("endpointMode")
            data.setdefault("gene_mode", mode)
            data.setdefault("scope_endpoint_mode", mode)
        elif "scope_endpoint_mode" in data:
            data.setdefault("gene_mode", data["scope_endpoint_mode"])
        return data


def normalize_filters(value: SearchFilters | dict[str, Any] | None) -> dict[str, Any]:
    model = value if isinstance(value, SearchFilters) else SearchFilters.model_validate(value or {})
    return model.model_dump()


class EntityIdentifier(APIModel):
    id: str | None = None
    entityPk: str | None = None
    identifier: str | None = None
    identifierType: str | None = None
    type: str | None = None
    curie: str | None = None
    source: str | None = None
    isCanonical: bool | None = None


class MolecularIdentifier(APIModel):
    ns: str
    id: str


class MolecularCoordinateReference(APIModel):
    identifier: MolecularIdentifier | None = None
    coordinate_system: str | None = None
    position_base: int | None = None


class MolecularModification(APIModel):
    term: str | None = None
    residue: str | None = None
    position: int | None = None
    end_position: int | None = None
    coordinate_reference: MolecularCoordinateReference | None = None
    description: str | None = None


class MolecularVariant(APIModel):
    identifier: MolecularIdentifier | None = None
    reference: str | None = None
    alternate: str | None = None
    position: int | None = None
    end_position: int | None = None
    coordinate_reference: MolecularCoordinateReference | None = None
    description: str | None = None


class MolecularRegion(APIModel):
    type: str | None = None
    identifier: MolecularIdentifier | None = None
    position: int | None = None
    end_position: int | None = None
    coordinate_reference: MolecularCoordinateReference | None = None
    description: str | None = None


class MolecularForm(APIModel):
    """Occurrence context. Missing fields assert neither canonical isoform nor wild type."""

    @model_validator(mode="before")
    @classmethod
    def unspecified_lists(cls, value):
        if isinstance(value, dict):
            value = dict(value)
            for field in ("sequence_identifiers", "modifications", "variants", "regions"):
                if value.get(field) is None:
                    value[field] = []
        return value

    protein_entity_key: str | None = None
    transcript_entity_key: str | None = None
    isoform_identifier: MolecularIdentifier | None = None
    sequence_identifiers: list[MolecularIdentifier] = Field(default_factory=list)
    modifications: list[MolecularModification] = Field(default_factory=list)
    variants: list[MolecularVariant] = Field(default_factory=list)
    regions: list[MolecularRegion] = Field(default_factory=list)


class EntityMolecularEvidence(APIModel):
    source: str | None = None
    dataset: str | None = None
    row_id: str | None = None
    upstream_id: str | None = None
    annotations: list[dict[str, Any]] = Field(default_factory=list)
    molecular_form: MolecularForm | None = None


class EntitySummary(APIModel):
    entityPk: str
    referenceEntityKey: str | None = None
    geneReferenceKeys: list[str] = Field(default_factory=list)
    molecularEvidence: list[EntityMolecularEvidence] = Field(default_factory=list)
    molecularEvidenceTotal: int = 0
    canonicalIdentifier: str | None = None
    canonicalIdentifierType: str | None = None
    entityType: str | None = None
    taxonomyId: str | None = None
    taxonomyName: str | None = None
    label: str | None = None
    displayName: str | None = None
    primaryIdentifier: str | None = None
    primaryNamespace: str | None = None
    resolutionStatus: str | None = None
    entityFacetHints: dict[str, list[str]] = Field(default_factory=dict)
    relationCount: int = 0
    parentCount: int = 0
    childCount: int = 0
    sourceCount: int = 0
    resources: list[str] = Field(default_factory=list)
    taxon: str | None = None
    ontologyHierarchy: dict[str, Any] | None = None
    annotations: list[dict[str, Any]] = Field(default_factory=list)
    sourceEntityPks: list[str] = Field(default_factory=list)
    identifiersTotal: int = 0
    annotationsTotal: int = 0
    entityAttributes: list[dict[str, Any]] | None = None
    description: str | None = None
    hasHierarchy: bool = False
    sources: list[str] = Field(default_factory=list)
    identifiers: list[EntityIdentifier] = Field(default_factory=list)


class EntitySearchRow(APIModel):
    entity_key: str | None = None
    label: str | None = None
    entity_type: str | None = None
    namespace: str | None = None
    identifier: str | None = None
    taxon: str | None = None


class EntitySearchResponse(APIModel):
    entities: list[EntitySummary] = Field(default_factory=list)
    nextCursor: EntitySearchCursor | None = None
    total: int | None = None
    elapsed_ms: float | None = None
    rows: list[EntitySearchRow] = Field(default_factory=list)
    count: int | None = None


class EntityExamplesResponse(APIModel):
    """The explorer's landing examples, as entities and as the grouped view's cards."""

    entities: list[EntitySummary] = Field(default_factory=list)
    groups: list[dict[str, Any]] = Field(default_factory=list)
    nextCursor: None = None
    total: int | None = None
    kind: str = "examples"


class EntitySearchRequest(APIModel):
    query: str = ""
    q: str = ""
    filters: SearchFilters = Field(default_factory=SearchFilters)
    resources: list[str] | None = None
    entity_types: list[str] | None = None
    taxon: str | None = None
    limit: int = Field(default=20, ge=1, le=1000)
    cursor: EntitySearchCursor | None = None
    shape: str | None = Field(default=None, description="Pass 'web' for the explorer payload.")


class EntityGroupsRequest(APIModel):
    strategy: Literal["auto", "chemical_connectivity", "gene_reference"] = "chemical_connectivity"
    query: str = ""
    filters: SearchFilters = Field(default_factory=SearchFilters)
    resources: list[str] | None = None
    limit: int = Field(default=20, ge=1, le=100)
    cursor: str | None = None
    group_key: str | None = None
    member_cursor: str | None = None
    member_limit: int = Field(default=5, ge=1, le=100)
    include_details: bool = False
    detail_limit: int = Field(default=20, ge=1, le=500)
    detail_offset: int = Field(default=0, ge=0)
    detail_field: DetailField | None = None


class EntityPksRequest(APIModel):
    pks: list[str | int] = Field(default_factory=list)
    entityPks: list[str | int] = Field(default_factory=list)


class GroupRelationshipsRequest(APIModel):
    strategy: Literal["auto", "chemical_connectivity", "gene_reference"] = "chemical_connectivity"
    member_keys: list[str] = Field(default_factory=list)
    group_key: str | None = None
    query: str = ""
    filters: SearchFilters = Field(default_factory=SearchFilters)
    resources: list[str] | None = None
    limit: int = Field(default=50, ge=1, le=100)
    offset: int = Field(default=0, ge=0)


class EntityPublicIdsRequest(APIModel):
    public_ids: list[str] = Field(default_factory=list)
    publicIds: list[str] = Field(default_factory=list)


class EntityResolveRequest(APIModel):
    identifiers: list[str] = Field(default_factory=list)


class EntityDetailsResponse(APIModel):
    relationships: list[dict[str, Any]] = Field(default_factory=list)
    relationshipsTotal: int = 0
    entity: EntitySummary | dict[str, Any] | None = None
    summary: dict[str, Any] = Field(default_factory=dict)
    annotations: list[dict[str, Any]] = Field(default_factory=list)


class EntitiesResponse(APIModel):
    entities: list[EntitySummary] = Field(default_factory=list)
    matches: list[dict[str, Any]] = Field(default_factory=list)


class EntityFilterOptions(APIModel):
    entity_types: list[str] = Field(default_factory=list)
    sources: list[str] = Field(default_factory=list)
    taxonomy_ids: list[str] = Field(default_factory=list)


class RelationSummary(APIModel):
    displayLabel: str | None = None
    relationPk: str
    subjectEntityPk: str | None = None
    subjectReferenceEntityKey: str | None = None
    objectReferenceEntityKey: str | None = None
    predicate: str | None = None
    objectEntityPk: str | None = None
    relationCategory: str | None = None
    participantTypes: list[str] = Field(default_factory=list)
    evidenceCount: int | None = None
    interactionClass: str | None = None
    isDirected: bool = False
    sign: int = 0
    sources: list[str] = Field(default_factory=list)
    qualifiers: dict[str, str] = Field(
        default_factory=dict,
        description="Effect qualifiers keyed by term: object_direction_qualifier, "
        "object_aspect_qualifier, causal_mechanism_qualifier.",
    )


class RelationSearchRequest(APIModel):
    filters: SearchFilters = Field(default_factory=SearchFilters)
    resources: list[str] | None = None
    limit: int = Field(default=20, ge=1, le=1000)
    offset: int = Field(default=0, ge=0)


class RelationRow(APIModel):
    relation: RelationSummary
    subjectEntity: EntitySummary
    objectEntity: EntitySummary


class RelationSearchResponse(APIModel):
    relations: list[RelationSummary] = Field(default_factory=list)
    rows: list[RelationRow] = Field(default_factory=list)
    total: int = 0
    nextCursor: str | None = None
    elapsed_ms: float | None = None


class RelationFilterOptions(APIModel):
    predicatesByCategory: dict[str, list[str]] = Field(default_factory=dict)
    sources: list[str] = Field(default_factory=list)
    interactionTypes: list[str] = Field(default_factory=list)


class FacetCount(APIModel):
    facetName: str
    facetValue: str
    facetLabel: str | None = None
    facetCategory: str | None = None
    scopedCount: int = 0


class ScopedEntityFacetsRequest(APIModel):
    entityIds: list[str | int] = Field(default_factory=list)
    annotationTermIds: list[str] = Field(default_factory=list)
    entityTypes: list[str] = Field(default_factory=list)
    sources: list[str] = Field(default_factory=list)
    ncbi_tax_id: list[str] = Field(default_factory=list)
    query: str = ""
    facetLimit: int | None = None


class ScopedRelationFacetsRequest(APIModel):
    taxonomyLimit: int | None = Field(default=None, ge=1, le=10000)
    taxonomyQuery: str = ""
    entityIds: list[str | int] = Field(default_factory=list)
    entity_ids: list[str | int] = Field(default_factory=list)
    endpointMode: Literal["any", "both"] | None = "any"
    mode: Literal["union", "intersection"] | None = None
    annotationTermIds: list[str] = Field(default_factory=list)
    predicates: list[str] = Field(default_factory=list)
    relation_categories: list[str] = Field(default_factory=list)
    object_aspect_qualifier: list[str] = Field(default_factory=list)
    object_direction_qualifier: list[str] = Field(default_factory=list)
    causal_mechanism_qualifier: list[str] = Field(default_factory=list)
    interactionTypes: list[str] = Field(default_factory=list)
    sources: list[str] = Field(default_factory=list)
    taxonomyIds: list[str] = Field(default_factory=list)
    filters: SearchFilters | None = None
    resources: list[str] | None = None


class PrototypeFacetsResponse(APIModel):
    categoryCounts: dict[str, int] = Field(default_factory=dict)
    predicateCounts: dict[str, int] = Field(default_factory=dict)
    signCounts: dict[str, int] = Field(default_factory=dict)
    elapsed_ms: float | None = None


class SelectionScopeRequest(APIModel):
    entityPks: list[str | int] = Field(default_factory=list)
    annotationTermIds: list[str] = Field(default_factory=list)
    includeAssociatedEntities: bool = True
    includeMembersParticipants: bool | None = None
    mode: Literal["union", "intersection"] | None = None


class SelectionScopeResponse(APIModel):
    entityPks: list[str] = Field(default_factory=list)
    seedEntityPks: list[str] = Field(default_factory=list)
    termEntityPks: list[str] = Field(default_factory=list)
    ontologyTermIds: list[str] = Field(default_factory=list)
    criteriaCount: int = 0
    expandedEntityCount: int = 0


class OntologySearchRequest(APIModel):
    query: str = ""
    q: str = ""
    prefixes: list[str] | None = None
    ontologyIds: list[str] | None = None
    limit: int | None = Field(default=None, ge=1, le=1000)
    offset: int | None = Field(default=None, ge=0)
    entityPks: list[str | int] = Field(default_factory=list)
    termIds: list[str] = Field(default_factory=list)
    selectionScope: dict[str, Any] | None = None


class OntologyTreeRequest(APIModel):
    term_ids: list[str] = Field(default_factory=list)
    termIds: list[str] = Field(default_factory=list)
    ontologyId: str | None = None
    ontology_id: str | None = None


class TermsRequest(APIModel):
    term_ids: list[str] = Field(default_factory=list)
    termIds: list[str] = Field(default_factory=list)


class TermsResponse(APIModel):
    terms: dict[str, Any] = Field(default_factory=dict)


class ResourceFile(APIModel):
    name: str
    url: str | None = Field(
        None,
        description="Immutable versioned artifact URL for downloads and remote Parquet queries, when static hosting is configured.",
    )
    size_bytes: int = 0
    rows: int = 0
    columns: list[dict[str, Any]] = Field(default_factory=list)


class ResourceTag(APIModel):
    id: str
    label: str
    dimension: Literal["topic", "content", "molecule", "knowledge_origin"]
    description: str


LicenseUseStatus = Literal["allowed", "requires_permission", "not_allowed", "unknown"]


class ResourceLicenseUse(APIModel):
    academic: LicenseUseStatus = "unknown"
    commercial: LicenseUseStatus = "unknown"


class ResourceRecord(APIModel):
    description: str = ""
    tags: list[ResourceTag] = Field(default_factory=list)
    license_use: ResourceLicenseUse = Field(default_factory=ResourceLicenseUse)
    queryable: bool = True
    resolution_stats: dict[str, Any] | None = None
    website: str | None = None
    license: str | None = None
    license_url: str | None = None
    input_module_url: str | None = None
    downloaded_at: str | None = None
    metadata_source: str | None = None
    max_records: int | None = None
    sample_build: bool | None = None
    dataset_subset: list[str] | None = None
    resource_id: str | None = None
    resource_name: str | None = None
    display_name: str | None = None
    key: str | None = None
    resource: str | None = None
    version: str | None = None
    entity_count: int | None = None
    interaction_count: int | None = None
    entities_count: int | None = None
    relations_count: int | None = None
    total_size_bytes: int | None = None
    files: list[ResourceFile] = Field(default_factory=list)


class ResourcesResponse(APIModel):
    resources: list[ResourceRecord] = Field(default_factory=list)


class ResourceFilesResponse(APIModel):
    resource_id: str
    version: str | None = None
    files: list[ResourceFile] = Field(default_factory=list)


class ResourceDownloadRequest(APIModel):
    resource_ids: list[str] = Field(default_factory=list)
    include_evidence: bool = Field(
        False,
        description="Include evidence_payloads.parquet in the zip. Omitted by default.",
    )


class StatsSource(APIModel):
    slug: str
    short: str | None = None
    full: str | None = None
    entityCount: int = 0
    interactionCount: int = 0
    associationCount: int = 0
    identifierCount: int = 0
    ontologyTermCount: int = 0


class StatsEntityType(APIModel):
    entityType: str
    count: int


class StatsInteractionType(APIModel):
    interactionType: str | None = None
    interactionClass: str | None = None
    count: int = 0


class BuildManifest(APIModel):
    buildId: str
    builtAt: str | None = None
    partialBuild: bool = False
    engine: str | None = None
    resources: list[str] = Field(default_factory=list)


class ExportRequest(APIModel):
    filters: SearchFilters = Field(default_factory=SearchFilters)
    resources: list[str] | None = None
    format: Literal["parquet", "arrow", "csv", "tsv", "json"] = "parquet"


class RelationMolecularEvidence(APIModel):
    relationPk: str
    relationEvidencePk: str
    source: str
    dataset: str | None = None
    rowId: str | None = None
    upstreamId: str | None = None
    subjectMolecularForm: MolecularForm | None = None
    objectMolecularForm: MolecularForm | None = None
    subjectAttributes: list[dict[str, Any]] = Field(default_factory=list)
    objectAttributes: list[dict[str, Any]] = Field(default_factory=list)
    recordAttributes: list[dict[str, Any]] = Field(default_factory=list)
    evidence: list[dict[str, Any]] = Field(default_factory=list)


class RelationEvidenceResponse(APIModel):
    evidence: list[RelationMolecularEvidence] = Field(default_factory=list)
    annotations: list[dict[str, Any]] = Field(default_factory=list)


class RelationPayloadsResponse(APIModel):
    relationPk: str
    payloads: list[dict[str, Any]] = Field(default_factory=list)


class AdminJobRequest(APIModel):
    action: Literal["export_hubs", "build_library", "build_resource", "build_resources"]
    hubs: list[str] | None = None
    sources: list[str] | None = None
    source: str | None = None
    version: str | None = Field(default=None, pattern=r"^[0-9]+(?:\.[0-9]+)*$")
    versions: dict[str, str] | None = None
    max_records: int | None = Field(default=None, ge=0)
    batch_size: int | None = Field(default=None, ge=1)
    parallel: int | None = Field(default=1, ge=1, le=32)
    build_library: bool = True
    include_dictionaries: bool = True
    force_refresh: bool = False


class OntologyTerm(APIModel):
    entityPk: str
    termId: str
    ontologyPrefix: str
    ontologyId: str
    label: str | None = None
    definition: str | None = None
    synonyms: list[str] = Field(default_factory=list)
    sources: list[str] = Field(default_factory=list)
    annotatedEntityCount: int = 0
    annotatedRelationCount: int = 0
    annotatedItemCount: int = 0


class OntologyChild(APIModel):
    id: str
    termId: str
    name: str
    label: str
    entityPk: str
    ontologyId: str


class OntologyChildrenResponse(APIModel):
    termId: str
    children: list[OntologyChild] = Field(default_factory=list)
    total: int = 0
    nextCursor: int | None = None


class AdminStage(APIModel):
    id: str
    status: str
    message: str = ""
    current: int | float | None = None
    total: int | float | None = None
    counts: dict[str, Any] = Field(default_factory=dict)
    started_at: float | None = None
    finished_at: float | None = None
    elapsed_seconds: float | None = None


class AdminJobResponse(APIModel):
    id: str
    action: str
    params: dict[str, Any] = Field(default_factory=dict)
    status: Literal["queued", "running", "done", "failed", "cancelled"]
    stages: list[AdminStage] = Field(default_factory=list)
    logs: list[str] = Field(default_factory=list)
    result: Any = None
    error: str | None = None
    created_at: float
    started_at: float | None = None
    finished_at: float | None = None
    elapsed_seconds: float = 0
    seq: int = 0
    cancel_requested: bool = False
    log_path: str | None = None


class AdminJobsResponse(APIModel):
    job: AdminJobResponse | None = None
    jobs: list[AdminJobResponse] = Field(default_factory=list)
