/** Identifier type vocabulary mapping and helpers */

export const IDENTIFIER_SLUGS: Record<string, string> = {
  uniprot: 'UniProt',
  genesymbol: 'Gene Symbol',
  entrez: 'Entrez Gene',
  ensg: 'Ensembl Gene',
  chebi: 'ChEBI',
  chembl: 'ChEMBL',
  pubchem: 'PubChem',
  inchikey: 'InChIKey',
  hgnc: 'HGNC',
  hmdb: 'HMDB',
  kegg: 'KEGG',
  kegg_pathway: 'KEGG pathway',
  kegg_reaction: 'KEGG reaction',
  rhea: 'Rhea',
  reactome: 'Reactome',
  lipidmaps: 'LIPID MAPS',
  swisslipids: 'SwissLipids',
  mirbase: 'miRBase',
  cas: 'CAS',
  bigg: 'BiGG',
  ec: 'EC',
  pfocr: 'PFOCR',
  wikipathways: 'WikiPathways',
  ensembl: 'Ensembl',
  metanetx: 'MetaNetX',
  chembl_target: 'ChEMBL target',
  name: 'Name',
  synonym: 'Synonym',
  smiles: 'SMILES',
  inchi: 'InChI',
  bindingdb: 'BindingDB',
  pubchem_substance: 'PubChem substance',
  ramp: 'RaMP',
  ramp_gene: 'RaMP gene',
  goslin: 'Goslin lipid name',
  genbank: 'GenBank',
  genbank_gi: 'GenBank GI',
  'uniprot-sec': 'UniProt secondary accession',
  uniprot_entry: 'UniProt entry',
  uniprot_trembl: 'UniProt TrEMBL',
  uniprot_keyword: 'UniProt keyword',
  'genesymbol-syn': 'Gene symbol synonym',
  refmet: 'RefMet',
  go: 'GO',
  mondo: 'MONDO',
  hpo: 'HPO',
  uberon: 'UBERON',
  cl: 'Cell Ontology',
  mi: 'PSI-MI',
  ncbitaxon: 'NCBI Taxonomy',
  mirbase_mature: 'miRBase mature',
  mirbase_precursor: 'miRBase precursor',
  kegg_gene: 'KEGG gene',
  kegg_orthology: 'KEGG orthology',
  kegg_drug: 'KEGG drug',
  kegg_glycan: 'KEGG glycan',
  foodb: 'FooDB',
  intact: 'IntAct',
  mint: 'MINT',
  signor: 'SIGNOR',
  corum: 'CORUM',
  complexportal: 'Complex Portal',
  bigg_reaction: 'BiGG reaction',
  bigg_metabolite: 'BiGG metabolite',
  metanetx_reaction: 'MetaNetX reaction',
  vmh_reaction: 'VMH reaction',
  seed_reaction: 'SEED reaction',
  seed_compound: 'SEED compound',
  metacyc: 'MetaCyc',
  metacyc_reaction: 'MetaCyc reaction',
  sabiork_reaction: 'SABIO-RK reaction',
  sabiork_compound: 'SABIO-RK compound',
  human_gem_reaction: 'Human-GEM reaction',
  human_gem_metabolite: 'Human-GEM metabolite',
  reactome_id: 'Reactome ID',
  biopax_physical_entity: 'BioPAX physical entity',
  chemspider: 'ChemSpider',
  drugbank: 'DrugBank',
  drugcentral: 'DrugCentral',
  guidetopharma: 'Guide to Pharmacology',
  guidetopharma_target: 'Guide to Pharmacology target',
  chembl_component: 'ChEMBL target component',
  chembl_variant: 'ChEMBL variant',
  chemont: 'ChemOnt',
  zinc: 'ZINC',
  enst: 'Ensembl transcript',
  ensp: 'Ensembl protein',
  refseq: 'RefSeq',
  refseq_protein: 'RefSeq protein',
  rnacentral: 'RNAcentral',
  brenda_protein_record: 'BRENDA protein record',
  ptfi: 'PTFI',
};

export function getIdentifierLabel(slug: string): string {
  return IDENTIFIER_SLUGS[slug.toLowerCase()] || slug;
}
