#!/usr/bin/env python3
"""Generate the web vocabulary from the same pinned schema as Python readers."""

import argparse
import json
from pathlib import Path

from omnipath_core.biolink import schema

TARGET = Path(__file__).resolve().parents[1] / "packages/web/src/lib/domain/biolink.generated.ts"


def terms(view, elements, *, predicates=False):
    records, lookup = {}, {}
    for name, element in sorted(elements.items()):
        if predicates and (
            element.deprecated or "related to" not in view.slot_ancestors(name, reflexive=True)
        ):
            continue
        canonical = name.lower().replace(" ", "_")
        curie = str(view.get_uri(element, expand=False))
        records[canonical] = dict(
            canonical=canonical,
            label=name[0].upper() + name[1:],
            curie=curie,
            description=str(element.description or ""),
        )
        for key in (name, canonical, curie):
            lookup[key.lower()] = canonical
    return records, lookup


def generate():
    view = schema()
    text = f"// Generated by scripts/sync_biolink.py from Biolink {view.schema.version}. Do not edit.\n\n"
    text += "export interface BiolinkTerm { canonical: string; label: string; curie: string; description: string; }\n\n"
    for name, alias, elements, predicates in (
        ("BIOLINK_PREDICATES", "PREDICATE_LOOKUP", view.all_slots(), True),
        ("BIOLINK_ENTITIES", "ENTITY_LOOKUP", view.all_classes(), False),
        ("BIOLINK_SLOTS", "SLOT_LOOKUP", view.all_slots(), False),
    ):
        records, lookup = terms(view, elements, predicates=predicates)
        for constant, data, value_type in (
            (name, records, "BiolinkTerm"),
            (alias, lookup, "string"),
        ):
            text += f"export const {constant}: Record<string, {value_type}> = {json.dumps(data, ensure_ascii=False, indent=2)};\n\n"
    return text.rstrip() + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = generate()
    if args.check:
        if TARGET.read_text() != generated:
            raise SystemExit("Web Biolink vocabulary is stale; run python scripts/sync_biolink.py")
        print("Web Biolink vocabulary is current")
    else:
        TARGET.write_text(generated)


if __name__ == "__main__":
    main()
