#!/usr/bin/env python3
"""PyPath Resource Discovery Tool.

Lists all available PyPath modules and functions, writing them to a file
for easy reference when adding resources to databases.

Usage:
    python tools/list_pypath_resources.py
    python tools/list_pypath_resources.py --output pypath_resources.txt
"""

import sys
import logging
from pathlib import Path
import pkgutil
import argparse

# Add parent directory to path
sys.path.append(str(Path(__file__).parent.parent))

import pypath.inputs

__all__ = [
    'discover_all_resources',
    'main',
    'write_resources_file',
    'write_summary_stats',
]


def discover_all_resources() -> dict[str, list[tuple[str, str]]]:
    """Discover all PyPath modules and their callable functions.

    Returns:
        Dict mapping module names to list of (function_name, description) tuples
    """
    logger = logging.getLogger(__name__)
    resources = {}

    logger.info('Discovering PyPath resources...')

    for _importer, modname, _ispkg in pkgutil.iter_modules(
        pypath.inputs.__path__
    ):
        try:
            # Import the module
            module = __import__(f'pypath.inputs.{modname}', fromlist=[''])

            functions = []

            # Find all callable functions
            for attr_name in dir(module):
                if attr_name.startswith('_'):
                    continue

                attr = getattr(module, attr_name)

                # Only include callables
                if not callable(attr):
                    continue

                # Skip classes that are namedtuple definitions
                if isinstance(attr, type) and issubclass(attr, tuple):
                    continue

                # Get a brief description
                description = ''
                try:
                    if hasattr(attr, '__doc__') and attr.__doc__:
                        # Get first line of docstring
                        description = attr.__doc__.split('\n')[0][:80]
                    elif (
                        hasattr(attr, 'func')
                        and hasattr(attr.func, '__doc__')
                        and attr.func.__doc__
                    ):
                        # For partials, get docstring from base function
                        description = attr.func.__doc__.split('\n')[0][:80]
                    else:
                        # Basic type description
                        description = f'{type(attr).__name__}'
                except (AttributeError, TypeError):
                    description = 'No description'

                functions.append((attr_name, description))

            if functions:
                resources[modname] = sorted(functions)
                logger.debug(f'Found {len(functions)} functions in {modname}')

        except (ImportError, AttributeError) as e:
            logger.debug(f'Could not process module {modname}: {e}')

    logger.info(
        f'Discovered {len(resources)} modules with {sum(len(funcs) for funcs in resources.values())} functions'
    )
    return resources


def write_resources_file(
    resources: dict[str, list[tuple[str, str]]], output_path: Path
) -> None:
    """Write resources to a nicely formatted text file.

    Args:
        resources: Dict of module -> [(function, description), ...]
        output_path: Where to write the file
    """
    with open(output_path, 'w') as f:
        f.write('# PyPath Resources - Available Modules and Functions\n')
        f.write('# Generated by tools/list_pypath_resources.py\n')
        f.write(
            f'# Total: {len(resources)} modules, {sum(len(funcs) for funcs in resources.values())} functions\n'
        )
        f.write('\n')
        f.write('Usage:\n')
        f.write('  # Add specific function:\n')
        f.write(
            '  python database_manager.py add-resources --database mydb --resources module.function\n'
        )
        f.write('\n')
        f.write('  # Add entire module:\n')
        f.write(
            '  python database_manager.py add-resources --database mydb --resources module\n'
        )
        f.write('\n')
        f.write('=' * 80)
        f.write('\n\n')

        # Write each module
        for module_name in sorted(resources.keys()):
            functions = resources[module_name]

            f.write(f'## {module_name} ({len(functions)} functions)\n')
            f.write('-' * (len(module_name) + 20))
            f.write('\n')

            for func_name, description in functions:
                f.write(f'  {module_name}.{func_name:<30} - {description}\n')

            f.write('\n')


def write_summary_stats(
    resources: dict[str, list[tuple[str, str]]], output_path: Path
) -> None:
    """Write summary statistics to console and optionally to file."""

    # Calculate stats
    total_modules = len(resources)
    total_functions = sum(len(funcs) for funcs in resources.values())

    # Top modules by function count
    top_modules = sorted(
        [(mod, len(funcs)) for mod, funcs in resources.items()],
        key=lambda x: x[1],
        reverse=True,
    )[:10]

    print('\n📊 PyPath Resources Summary:')
    print(f'   Total modules: {total_modules}')
    print(f'   Total functions: {total_functions}')
    print(
        f'   Average functions per module: {total_functions / total_modules:.1f}'
    )
    print('\n🔝 Top modules by function count:')
    for module, count in top_modules:
        print(f'   {module:<20} - {count:>3} functions')

    print(f'\n📁 Full list written to: {output_path}')


def main() -> None:
    """Main entry point for listing PyPath resources."""
    parser = argparse.ArgumentParser(
        description='List all available PyPath resources',
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )

    parser.add_argument(
        '--output',
        '-o',
        default='pypath_resources.txt',
        help='Output file path (default: pypath_resources.txt)',
    )

    parser.add_argument(
        '--verbose', '-v', action='store_true', help='Enable verbose logging'
    )

    parser.add_argument(
        '--search',
        '-s',
        help='Search for modules/functions containing this term',
    )

    args = parser.parse_args()

    # Setup logging
    level = logging.DEBUG if args.verbose else logging.INFO
    logging.basicConfig(
        level=level,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    )

    try:
        # Discover all resources
        resources = discover_all_resources()

        # Write to file
        output_path = Path(args.output)
        write_resources_file(resources, output_path)

        # Show summary
        write_summary_stats(resources, output_path)

    except KeyboardInterrupt:
        print('\nInterrupted by user')
        sys.exit(1)
    except (ImportError, AttributeError, OSError) as e:
        logger = logging.getLogger(__name__)
        logger.error(f'Error: {e}')
        if args.verbose:
            logger.exception('Full traceback:')
        sys.exit(1)


if __name__ == '__main__':
    main()
